sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4.1.1'
before_install:
  - npm i -g npm@^2.0.0
  - npm install --save-dev eslint-config-airbnb eslint-plugin-react eslint@^1.0.0
before_script:
  - npm prune
script:
  - npm test
  - eslint . --ext .jsx
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

